generated = ""
source = ""

[settings]
plugin_dir = "C:/Programs/EDMarketConnector/plugins"
ui_scale = 100
dark_text = "#ebbc76"
dark_highlight = "#b0cfd9"
station_provider = "Inara"
shipyard_provider = "Coriolis"
system_provider = "Inara"
cmdrs = [
    "DEE.COVAN",
]
edsm_cmdrs = [
    "DEE.COVAN",
]
edsm_usernames = [
    "DEE.COVAN",
]
edsm_apikeys = [
    "",
]
fdev_apikeys = [
    "57411003-251f-432c-b278-290b3fc1fbbc",
]
prefsversion = 4
output = 6161
mkt_export_type = "SEMICOLON"
outdir = ""
journaldir = ""
capi_fleetcarrier = true
hotkey_code = 76
hotkey_mods = 6
hotkey_always = 0
hotkey_mute = 1
beta_optin = 0
loglevel = "WARNING"
language = ""
hide_private_group = false
hide_multicrew_captain = false
ui_transparency = 80
always_ontop = true
minimize_system_tray = true
no_systray = false
theme = 1
coriolis_normal_url = "https://coriolis.io/import?data="
coriolis_beta_url = "https://beta.coriolis.io/import?data="
coriolis_overide_url_selection = "auto"
edastro_send = 1
edsm_out = 1
inara_out = 1
geometry = "+-3+1"
querytime = 1783605184
inara_cmdrs = [
    "DEE.COVAN",
]
inara_apikeys = [
    "6731781pkn40gs04gw0g4088k0o844ccck04oko",
]
pioneer_min_value = 500000
pioneer_shorten = true
pioneer_details = false
pioneer_biological = true
pioneer_star_descriptors = true
pioneer_carrier_values = false
pioneer_map_counter = false
pioneer_max_sell_events = 5
pioneer_overlay = true
pioneer_overlay_color = "#cdd9e2"
pioneer_overlay_anchor_x = 40
pioneer_overlay_anchor_y = 320
fleetcarrierquerytime = 1783608944
edraudiofeedbackvolume = "soft"
hitsoverlayduration = "4"
edremail = "dmitry.cheva@gmail.com"
edrpassword = "Gfhjkm1976!!!"
edrvisualfeedback2 = "Enabled"
edraudiofeedback = "True"
edrredactmyinfo = "Auto"
edrcrimesreporting = "True"
edrfcjumppsa = "Public"
edrtopplanetcountinsystemreport = "5"
edrvisualaltfeedback = "True"
disable_autoappupdatecheckingame = 1
core_updater_disable_in_game = 1
